### ISSUE TITLE
What do you mean by xiaojiba?

### ISSUE THREAD

**Issue by hanayashiki** [erwanvivien/xiaojiba.dev#2]
It literally means little dick in Chinese. I wonder if it is some kind of joke

**Comment by erwanvivien** [comment]
Nǐ hǎo, wǒ zhīdào
Dāngnián wǒ xué zhōngwén de shíhòu, zhè shì wǒ xué de dì yī gè zānghuà

I kinda lost my chinese tho :)

**Comment by erwanvivien** [comment]
I'm still curious about how did you find this page ahah :)

**Comment by hanayashiki** [comment]
> I'm still curious about how did you find this page ahah :)

My colleague found this site's name interesting and told me

**Comment by erwanvivien** [comment]
Cool :)
